### ISSUE TITLE
When will training data be released?

### ISSUE THREAD

**Issue by Frank-Dz** [chenchao15/LPI#1]
Hi~ Thanks for your great work!
May I know when will you release the training data and deployment instructions?
Thank you!

**Comment by chenchao15** [comment]
Hi~ we will release the dataset and instructions in about two weeks

**Comment by Frank-Dz** [comment]
> Hi~ we will release the dataset and instructions in about two weeks

Hi ~ Seems like you have finished uploading everything~ Thank you!
